export * from './Home';
export * from './About';
export * from './Contacts';
export * from './Products';
export * from './Product';
export * from './Cart';
export * from './Login';
export * from './Dashboard';
export * from './Profile';